---
title: "Black Jack Ligue 1"
format:
  html:
    page-layout: full
    theme: default
    css: styles.css
execute:
  echo: false
  message: false
  warning: false
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(highcharter)
library(crosstalk)
library(reactable)
library(htmltools)
library(httr2)
library(rvest)
library(xlsx)
library(purrr)
library(stringr)
library(tidyr)
library(reticulate)
```


```{r}
data <- xlsx::read.xlsx("data.xlsx", sheetIndex = 1)

# python virtual env in .yaml for production
# virtualenv_install("21GoalsEnv", packages = c("pandas", "selenium",
#                                                "bs4", "lxml"))

use_virtualenv("21GoalsEnv")
scraper <- import("python_selenium")
```


```{r functions}
get_goal_by_round_link <- function(player_link){
  
  split_player_link = player_link %>% strsplit("/")
  base_link = paste(split_player_link[[1]][1:6],collapse = "/")
  goal_link = paste(base_link, "goallogs/dom_lg", paste0(split_player_link[[1]][7], "-Goal-Log"), sep = "/")
  
  return(goal_link)
  
}

get_dom_goal_link <- function(player_link){
  
  split_player_link = player_link %>% strsplit("/")
  base_link = paste(split_player_link[[1]][1:6],collapse = "/")
  goal_link = paste(base_link, "dom_lg", paste0(split_player_link[[1]][7], "-Domestic-League-Stats"), sep = "/")
  
  return(goal_link)
  
}

get_player_informations <- function(extract, season){
  
  df <- extract
  
  table_colnames = stringr::str_extract(names(df), "(?<=, ').*?(?=')")
  colnames(df) = table_colnames
  
  keep_vars = c("MP", "Min", "Gls", "PK", "PKatt", "xG")
  country = "FRA"
  
  df_goals <- df[,1:22] %>%
    filter(Season == season & grepl(country,Country)) %>%
    select(all_of(keep_vars)) %>%
    mutate(across(everything(), ~ ifelse(.x == "", 0, .x))) %>%
    mutate(Min = str_replace(Min, ",", "")) %>%
    mutate(across(all_of(keep_vars), as.numeric))
  
  if(nrow(df) == 0){
    df <- as.data.frame(matrix(0, nrow = 1, ncol = length(keep_vars)))
    colnames(df) <- keep_vars
  }
  
  return(df_goals)
  
}

get_goals_by_rounds <- function(extract){
  
  df_goals <- extract %>%
    select(Rk, Comp, Round, Date, xG) %>%
    filter(!is.na(Rk)) %>%
    filter(Comp == "Ligue 1") %>%
    mutate(Date = as.Date(Date)) %>%
    filter(Date > "2025-08-14") %>%
    group_by(Round) %>%
    summarise(goals = n())
  
  return(df_goals)
  
}

```


```{r}
data <- data %>%
  rowwise() %>%
  mutate(goal_link = get_dom_goal_link(link),
         round_goal_link = get_goal_by_round_link(link)) %>%
  ungroup()
```


```{r}
goal_links = unique(data$goal_link)
extract = scraper$extract_table_from_url(goal_links, table_id = "stats_standard_dom_lg", image='yes')

img_links <- extract[[2]]
df_informations <- lapply(extract[[1]], get_player_informations, season = "2025-2026")
df_informations <- do.call("rbind", df_informations) %>%
  select(Gls, xG, everything()) %>%
  mutate(goal_link = goal_links,
         img = img_links)

data <- data %>%
  left_join(df_informations, by = "goal_link")
```


```{r}
round_goal_links <- unique(data$round_goal_link)
extract <- scraper$extract_table_from_url(round_goal_links, table_id = "goallogs_goals")

df_informations <- lapply(extract[[1]], get_goals_by_rounds)
df_informations <- Map(
  function(df, link) {
    if (!is.null(df)) df$round_goal_link <- link
    df
  },
  df_informations,
  round_goal_links)

df_informations <- do.call("rbind", df_informations)

df_cumulative <- merge(data, df_informations, by = "round_goal_link") %>%
  group_by(player, Round) %>%
  summarise(goals = sum(goals), .groups = "drop") %>%
  mutate(Round = str_remove(Round, "Matchweek ") %>% as.numeric()) %>%
  arrange(player, Round) %>%
  group_by(player) %>%
  complete(Round = 1:34, fill = list(goals = 0)) %>%
  mutate(CumGoals = cumsum(goals)) %>%
  ungroup() %>%
  mutate(CumGoals = ifelse(Round <= max(Round[goals > 0]), CumGoals, NA))

```


::::: {.columns .responsive-columns}
::: {.column width="70%"}
```{r radar_chart}

df_group_by <- data %>%
  group_by(player) %>%
  summarise(sum_goals = sum(Gls, na.rm = TRUE))

highchart() %>%
  hc_chart(polar = TRUE, type = "line") %>%
  hc_xAxis(categories = df_group_by$player,
           tickmarkPlacement = "on",
           lineWidth = 0) %>%
  hc_yAxis(gridLineInterpolation = "polygon",
           lineWidth = 0,
           min = 0,
           max = 30,
           tickPositions = c(0, 21, 30),
           gridLineColor = "transparent",
           plotBands = list(
             list(from = 21,
                  to = 30,
                  color = "rgba(255, 0, 0, 0.2)",
                  label = list(text = "Au-dessus de 21",
                               style = list(color = "red")))),
           plotLines = list(
             list(value = 21,
                  color = "#B00020",
                  width = 2,
                  dashStyle = "Solid",
                  label = list(text = "Seuil : 21",
                               style = list(color = "#B00020",
                                            fontWeight = "bold"),
                               align = "right"),
                  zIndex = 5))) %>%
  hc_series(list(name = "Goals",
                 data = df_group_by$sum_goals,
                 pointPlacement = "on")) %>%
  hc_legend(enabled = FALSE) %>%
  hc_tooltip(shared = TRUE,
             pointFormat = "<span style='color:{series.color}'>{series.name}: <b>{point.y}</b><br/>")


```
:::

::: {.column width="30%"}
```{r table}
shared_data <- SharedData$new(data,
                              key = ~row.names(data),
                              group = "players_group")

filter_select("player_selector",
              "Select a player :",
              shared_data,
              ~player,
              multiple = FALSE)

# Bar chart for reactable
bar_chart <- function(label, width = "100%", height = "1rem", fill = "#00bfc4", background = NULL){
  bar <- div(style = list(background = fill, width = width, height = height))
  chart <- div(style = list(flexGrow = 1, marginLeft = "0.5rem", background = background), bar)
  div(style = list(display = "flex", alignItems = "center"), label, chart)
}


# Interactive data table
reactable(
  shared_data,
  columns = list(
    player = colDef(name = "Joueur", style = list(fontWeight = "bold"), show = FALSE),
    link = colDef(show = FALSE),
    img = colDef(show = FALSE),
    goal_link = colDef(show = FALSE),
    round_goal_link = colDef(show = FALSE),
    football_player = colDef(name = "Football Player", align = "left", cell = function(value, index){
      image <- img(src = data$img[index], style = "height: 24px;", alt = value)
      tagList(
        div(style = "display: inline-block; width: 45px", image),
        value
      )
    }),
    Gls = colDef(name = "Goals", cell = function(value){
      width <- paste0(value / max(data$Gls, na.rm = TRUE) * 100, "%")
      bar_chart(value, width = width)
    }),
    MP = colDef(name = "Matches Played"),
    Min = colDef(show = TRUE),
    xG = colDef(name = "Sum xG"),
    PK = colDef(name = "Penalty"),
    PKatt = colDef(name = "Penaltys Attempted")
  ),
  bordered = TRUE,
  highlight = TRUE,
  striped = TRUE,
  defaultPageSize = 4,
  style = list(fontFamily = "Arial", fontSize = "15px")
)

```
:::

::: {.center}
```{r}
df_list <- df_cumulative %>%
  group_by(player) %>%
  summarise(data = list(CumGoals), .groups = "drop")

theoretical_line <- data.frame(
  round = 1:34,
  theoretical = (21 / (34 - 1)) * (1:34 - 1)
)

# Création du graphique line chart
highchart() %>%
  hc_chart(type = "line") %>%
  hc_title(text = "Cumultaive Goals by Matchweek") %>%
  hc_xAxis(categories = paste("Round", sort(unique(df_cumulative$Round)))) %>%
  hc_yAxis(title = list(text = "Cumulative Goals"),
           min = 0,
           max = ifelse(max(df_cumulative$CumGoals)>20, max(df_cumulative$CumGoals) + 3, 22)) %>%
  hc_add_series_list(
    lapply(1:nrow(df_list), function(i) {
      list(
        name = df_list$player[i],
        data = df_list$data[[i]]
      )
    })
  ) %>%
  hc_add_series(
    name = "Theoritical goal",
    data = round(theoretical_line$theoretical, 2),
    color = "#B00020",
    lineWidth = 3,
    dashStyle = "ShortDot",
    marker = list(enabled = FALSE)
  ) %>%
  hc_add_series(
    type = "arearange",
    name = "Area under theoretical goal",
    data = lapply(1:34, function(i) {
      list(i - 1, 0, theoretical_line$theoretical[i])
    }),
    color = "rgba(240,240,240,0.3)",
    enableMouseTracking = FALSE,
    showInLegend = FALSE
  ) %>%
  hc_plotOptions(
    line = list(dataLabels = list(enabled = FALSE),
                marker = list(enabled = TRUE,
                              symbol = "circle",
                              radius = 4)),
    series = list(marker = list(enabled = TRUE))
  ) %>%
  hc_tooltip(shared = TRUE, crosshairs = TRUE) %>%
  hc_yAxis(plotLines = list(list(value = 21,
                                 color = "#B00020",
                                 width = 4))
  )
```

:::

To learn more about this game, see <https://www.21goals.app/>.
:::::
